package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class AcercaDe extends javax.swing.JDialog {

    
    public AcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setTitle("Acerca de Finance Manager");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        
        try {
            ImageIcon logo = new ImageIcon(getClass().getResource("/images/Logo.png"));
            Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH));
            jLabel_logo.setIcon(icono_logo);
        } catch (Exception e) {
            // Si falla la imagen, simplemente no muestra logo
        }
    }
    
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_acercaDe = new javax.swing.JTextArea();
        btn_cerrar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logo.setBackground(new java.awt.Color(252, 252, 252));
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 0, 90, 90));

        txtArea_acercaDe.setEditable(false);
        txtArea_acercaDe.setColumns(20);
        txtArea_acercaDe.setLineWrap(true);
        txtArea_acercaDe.setRows(5);
        txtArea_acercaDe.setText("Finance Manager v1.0\n\nAplicación de escritorio para la gestión y control de ingresos y egresos personales.\nPermite registrar movimientos financieros, aplicar filtros por tipo y fecha,\ny generar reportes en formato PDF.\n\nDesarrollado por Mario Alberto Melgarejo Villaseñor © 2026\n\nTecnologías utilizadas:\n- Java\n- Swing\n- SQLite\n- Apache PDFBox\n\nEste software es de uso personal.\nSe recomienda realizar respaldos periódicos de la base de datos.\nEl desarrollador no se responsabiliza por la pérdida de información.");
        txtArea_acercaDe.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtArea_acercaDe);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 200));

        btn_cerrar.setBackground(new java.awt.Color(70, 73, 75));
        btn_cerrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cerrar.setForeground(new java.awt.Color(242, 242, 242));
        btn_cerrar.setText("Cerrar");
        btn_cerrar.setBorder(null);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 325, 100, 30));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea_acercaDe;
    // End of variables declaration//GEN-END:variables
}
