package ventanas;

import clases.Movimientos;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class AgregarMovimiento extends javax.swing.JDialog {

    String tipo, comentarios;
    double cantidad;
    int idUsuario, validacion = 0;
    private Principal principal;

    public AgregarMovimiento(Principal parent, boolean modal, int idUsuario) {
        super(parent, modal);
        initComponents();

        this.idUsuario = idUsuario;
        this.principal = parent;

        setTitle("Agregar Movimiento");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //setSize(320,370);
        pack();
    }

    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tittle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_tipos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane_comentarios = new javax.swing.JTextPane();
        btn_agregarMovimiento = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_tittle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_tittle.setText("Agregar Movimiento");
        getContentPane().add(jLabel_tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setText("Tipo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cmb_tipos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmb_tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        getContentPane().add(cmb_tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 55, 210, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txt_cantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 105, 180, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Comentario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        textPane_comentarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(textPane_comentarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 70));

        btn_agregarMovimiento.setBackground(new java.awt.Color(39, 174, 96));
        btn_agregarMovimiento.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_agregarMovimiento.setForeground(new java.awt.Color(242, 242, 242));
        btn_agregarMovimiento.setText("Confirmar");
        btn_agregarMovimiento.setBorder(null);
        btn_agregarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 35));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarMovimientoActionPerformed
        // Validar saldo vacio

        validacion = 0;

        if (txt_cantidad.getText().trim().isEmpty()) {
            txt_cantidad.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {

            //obtener datos
            tipo = cmb_tipos.getSelectedItem().toString();
            comentarios = textPane_comentarios.getText().trim();
            try {
                cantidad = Double.parseDouble(txt_cantidad.getText().trim());
                if (cantidad <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad ingresada debe ser mayor que cero.\nPor favor ingrese un valor positivo.",
                            "Valor inválido",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "La cantidad debe contener solo números.\nPor favor ingrese un valor válido.",
                        "Formato incorrecto",
                        JOptionPane.WARNING_MESSAGE);
                txt_cantidad.setText("");
                return;
            }

            int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas guardar este movimiento?",
                    "Confirmación", JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION) {
                //Mandar datos
                Movimientos m = new Movimientos();
                boolean ok = m.agregarMovimiento(tipo, cantidad, comentarios, idUsuario);

                //verificar movimiento exitoso
                if (ok) {
                    JOptionPane.showMessageDialog(this, "Movimiento agregado exitosamente");
                    principal.mostrarSaldo();
                    principal.totalIngresos();
                    principal.totalEgresos();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo registrar el movimiento.\nInténtelo nuevamente.",
                            "Error al registrar movimiento",
                            JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                }
            } else {
                Limpiar();
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Faltan campos por completar.\nPor favor llene todos los datos antes de continuar.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);
            txt_cantidad.setBackground(Color.white);
        }
    }//GEN-LAST:event_btn_agregarMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarMovimiento;
    private javax.swing.JComboBox<String> cmb_tipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_tittle;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPane_comentarios;
    private javax.swing.JTextField txt_cantidad;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        textPane_comentarios.setText("");
        txt_cantidad.setText("");
        cmb_tipos.setSelectedIndex(0);
    }

}
