package ventanas;

import clases.Movimiento;
import clases.Movimientos;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.Locale;

public class DetallesMovimiento extends javax.swing.JDialog {

    int idMovimiento /*id_visual*/;
     NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.getDefault());

    public DetallesMovimiento(java.awt.Window parent, int idMovimiento, int id_visual) {
        super(parent, ModalityType.APPLICATION_MODAL);
        initComponents();

        this.idMovimiento = idMovimiento;
        
        setTitle("Detalles del movimiento " + id_visual);
        jLabel_titulo.setText("Detalles del movimiento: " + id_visual);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //setSize(380,370);
        pack();

        mostrarDetalles();
    }

    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    private void mostrarDetalles() {
        Movimientos m = new Movimientos();
        Movimiento mov = m.obtenerDetallesMovimiento(idMovimiento);

        if (mov != null) {

            jLabel_fechaRegistro.setText(mov.getFecha());

            jLabel_cantidad.setText(nf.format(mov.getMonto()));
            jLabel_tipo.setText(mov.getTipo());
            textPane_comentarios.setText(mov.getComentarios());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_fechaRegistro = new javax.swing.JLabel();
        jLabel_cantidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane_comentarios = new javax.swing.JTextPane();
        jLabel_tipo = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setText("Detalles del movimiento: ");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Fecha de registro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Comentarios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel_fechaRegistro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_fechaRegistro.setText("00/00/0000");
        getContentPane().add(jLabel_fechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 100, -1));

        jLabel_cantidad.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_cantidad.setText("$000.00");
        getContentPane().add(jLabel_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, -1));

        textPane_comentarios.setEditable(false);
        textPane_comentarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(textPane_comentarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, 90));

        jLabel_tipo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(jLabel_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 100, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_cantidad;
    private javax.swing.JLabel jLabel_fechaRegistro;
    private javax.swing.JLabel jLabel_tipo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPane_comentarios;
    // End of variables declaration//GEN-END:variables
}
