package ventanas;

import clases.Movimiento;
import clases.Movimientos;
import clases.ReportePDF;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class HistorialMovimientos extends javax.swing.JDialog {

    int idUsuario, contador = 1, idMovimiento, id_visual;
    List<Integer> ids = new ArrayList<>();
    List<Integer> idVisual = new ArrayList<>();
    List<String> anios = new ArrayList<>();
    List<Movimiento> listaMovimientos = new ArrayList<>();

    //Datos para PDF
    double totalIngresos, totalEgresos;
    String user, filtroTipo, filtroMes, filtroAnio, tipoAplicado, mesAplicado, anioAplicado;

    public static final String TIPO_INGRESO = "Ingreso";
    public static final String TIPO_EGRESO = "Egreso";
    public static final String TIPO_TODOS = "Todos";

    public static final String MES_TODOS = "Todos";
    public static final String ANIO_TODOS = "Todos";

    /**
     * Creates new form HistorialMovimientos
     */
    public HistorialMovimientos(java.awt.Frame parent, boolean modal, int idUsuario, String user) {
        super(parent, modal);
        initComponents();

        this.idUsuario = idUsuario;
        this.user = user;

        cargarMovimientos(null, null, null);
        actualizarLabelFiltro(null, HistorialMovimientos.MES_TODOS, HistorialMovimientos.ANIO_TODOS);

        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //setSize(550,400);
        pack();

        cmb_anio.removeAllItems();
        cmb_anio.addItem("Todos");

        Movimientos m = new Movimientos();
        anios = m.obtenerAniosUsuarios(idUsuario);

        for (String anio : anios) {
            cmb_anio.addItem(anio);
        }

        jLabel_sinRegistros.setVisible(false);

    }

    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_movimientos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmb_filtroBusqueda = new javax.swing.JComboBox<>();
        btn_aplicarFiltro = new javax.swing.JButton();
        jLabel_filtroDeBusqueda = new javax.swing.JLabel();
        btn_restablecerFiltro = new javax.swing.JButton();
        cmb_mes = new javax.swing.JComboBox<>();
        cmb_anio = new javax.swing.JComboBox<>();
        jLabel_sinRegistros = new javax.swing.JLabel();
        btn_exportarPdf = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setText("Historial de Movimientos");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jTable_movimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Tipo", "Monto", "Fecha"
            }
        ));
        jTable_movimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_movimientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_movimientos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 510, 145));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Filtrar movimientos por:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cmb_filtroBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ingreso", "Egreso" }));
        getContentPane().add(cmb_filtroBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 75, -1));

        btn_aplicarFiltro.setBackground(new java.awt.Color(52, 152, 219));
        btn_aplicarFiltro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_aplicarFiltro.setForeground(new java.awt.Color(242, 242, 242));
        btn_aplicarFiltro.setText("Aplicar filtro ");
        btn_aplicarFiltro.setBorder(null);
        btn_aplicarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicarFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aplicarFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 30));

        jLabel_filtroDeBusqueda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_filtroDeBusqueda.setText("Filtro:");
        getContentPane().add(jLabel_filtroDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        btn_restablecerFiltro.setBackground(new java.awt.Color(189, 195, 199));
        btn_restablecerFiltro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_restablecerFiltro.setForeground(new java.awt.Color(44, 62, 80));
        btn_restablecerFiltro.setText("Restablecer filtro ");
        btn_restablecerFiltro.setBorder(null);
        btn_restablecerFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restablecerFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_restablecerFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, 140, 30));

        cmb_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" }));
        getContentPane().add(cmb_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 75, -1));

        getContentPane().add(cmb_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 75, -1));

        jLabel_sinRegistros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_sinRegistros.setText("No se registraron movimientos en este período");
        getContentPane().add(jLabel_sinRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 185, -1, -1));

        btn_exportarPdf.setBackground(new java.awt.Color(46, 125, 50));
        btn_exportarPdf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_exportarPdf.setForeground(new java.awt.Color(242, 242, 242));
        btn_exportarPdf.setText("Exportar a PDF");
        btn_exportarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportarPdfActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exportarPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 135, -1, 30));

        jLabel_wallpaper.setBackground(new java.awt.Color(245, 247, 250));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarMovimientos(String filtro, String mes, String anio) {

        DefaultTableModel modelo = (DefaultTableModel) jTable_movimientos.getModel();

        try {
            Movimientos m = new Movimientos();
            int movimientos = m.obtenerMovimientos(modelo, idUsuario, filtro, mes, anio, ids, idVisual);
            jLabel_sinRegistros.setVisible(movimientos == 0);

            listaMovimientos = m.getlistaMovimientos();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudieron cargar los movimientos.\n"
                    + "Verifique que el servicio MySQL esté activo y vuelve a intentarlo.\n" 
                    + "Si el problema persiste, reinicia la aplicación.",
                    "Error de carga",
                    JOptionPane.ERROR_MESSAGE);
            System.err.println(e);
        }

    }

    private void jTable_movimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_movimientosMouseClicked

        int fila = jTable_movimientos.rowAtPoint(evt.getPoint());

        if (fila >= 0) {
            idMovimiento = ids.get(fila);
            id_visual = idVisual.get(fila);
            abrirDetalles(idMovimiento, id_visual);
        }
    }//GEN-LAST:event_jTable_movimientosMouseClicked

    private void btn_aplicarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicarFiltroActionPerformed
        // TODO add your handling code here:

        //Para logica bd
        String tipo = cmb_filtroBusqueda.getSelectedItem().toString();
        String filtro = null;
        int mesIndex = cmb_mes.getSelectedIndex();
        String mes = null;
        String anioSel = cmb_anio.getSelectedItem().toString();
        String anio = null;

        //ParaPDF
        tipoAplicado = tipo;
        mesAplicado = cmb_mes.getSelectedItem().toString();
        anioAplicado = cmb_anio.getSelectedItem().toString();

        if (tipo.equals(HistorialMovimientos.TIPO_INGRESO)) {
            filtro = tipo;
        } else if (tipo.equals(HistorialMovimientos.TIPO_EGRESO)) {
            filtro = tipo;
        }

        if (mesIndex >= 1) {
            mes = String.format("%02d", mesIndex);
        }

        if (!anioSel.equals(HistorialMovimientos.ANIO_TODOS)) {
            anio = anioSel;
        }

        if (mes != null && anio == null) {
            JOptionPane.showMessageDialog(this,
                    "Para aplicar un filtro por mes, también debe seleccionar un año.\n"
                    + "Por favor, elige un año junto con el mes.",
                    "Filtro inválido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        cargarMovimientos(filtro, mes, anio);
        actualizarLabelFiltro(filtro, cmb_mes.getSelectedItem().toString(), cmb_anio.getSelectedItem().toString());
    }//GEN-LAST:event_btn_aplicarFiltroActionPerformed

    private void btn_restablecerFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restablecerFiltroActionPerformed

        cargarMovimientos(null, null, null);
        cmb_filtroBusqueda.setSelectedItem(HistorialMovimientos.TIPO_TODOS);
        cmb_mes.setSelectedItem(HistorialMovimientos.MES_TODOS);
        cmb_anio.setSelectedItem(HistorialMovimientos.ANIO_TODOS);

        String filtro = cmb_filtroBusqueda.getSelectedItem().toString();
        String mes = cmb_mes.getSelectedItem().toString();
        String anio = cmb_anio.getSelectedItem().toString();

        actualizarLabelFiltro(filtro, mes, anio);
    }//GEN-LAST:event_btn_restablecerFiltroActionPerformed

    //Obtener datos para el PDF
    public void obtenerDatos() {
        Movimientos m = new Movimientos();
        totalIngresos = m.calcularTotalIngresos(idUsuario);
        totalEgresos = m.calcularTotalEgresos(idUsuario);

        filtroTipo = tipoAplicado;
        filtroMes = mesAplicado;
        filtroAnio = anioAplicado;
    }

    private void btn_exportarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportarPdfActionPerformed
        // TODO add your handling code here:
        if (listaMovimientos.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay movimientos en la tabla para exportar.\n"
                    + "Aplique un filtro o registre movimientos antes de generar el PDF.",
                    "Exportación no disponible",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        obtenerDatos();
        ReportePDF.generarHistorial(user, filtroTipo, filtroMes, filtroAnio, totalIngresos, totalEgresos, listaMovimientos);
        JOptionPane.showMessageDialog(this,
                "PDF generado correctamente.\nEl archivo se guardó en el Escritorio.",
                "Exportación exitosa",
                JOptionPane.INFORMATION_MESSAGE);
        /*
        listaMovimientos - contiene todos los objetos Movimiento que se construyeron a partir de los registros de la base de datos.
        - Cada objeto tiene sus atributos: idMovimiento, tipo, monto, fecha, comentarios.
        - Esa lista se pasa completa al método ReportePDF.generarHistorial(...).
        Además de la lista, se mandan otros parámetros que complementan el reporte.
         */
    }//GEN-LAST:event_btn_exportarPdfActionPerformed

    private void actualizarLabelFiltro(String filtro, String mes, String anio) {

        StringBuilder contenido = new StringBuilder("Filtro: ");
        StringBuilder titulo = new StringBuilder("Historial de Movimientos - ");

        if (filtro != null) {
            contenido.append(filtro + " - ");
            titulo.append(filtro + " - ");
        } else {
            contenido.append(HistorialMovimientos.TIPO_TODOS + " - ");
            titulo.append(HistorialMovimientos.TIPO_TODOS + " - ");
        }

        if (!mes.equals(HistorialMovimientos.MES_TODOS)) {
            contenido.append(mes + " / ");
            titulo.append(mes + " / ");
        } else {
            contenido.append("");
            titulo.append("");
        }

        if (!anio.equals(HistorialMovimientos.ANIO_TODOS)) {
            contenido.append(anio.toString());
            titulo.append(anio.toString());
        } else {
            contenido.append(HistorialMovimientos.ANIO_TODOS);
            titulo.append(HistorialMovimientos.ANIO_TODOS);
        }

        jLabel_filtroDeBusqueda.setText(contenido.toString());
        setTitle(titulo.toString());

    }

    private void abrirDetalles(int idMovimiento, int id_visual) {
        DetallesMovimiento dm = new DetallesMovimiento(this, idMovimiento, id_visual);
        dm.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aplicarFiltro;
    private javax.swing.JButton btn_exportarPdf;
    private javax.swing.JButton btn_restablecerFiltro;
    private javax.swing.JComboBox<String> cmb_anio;
    private javax.swing.JComboBox<String> cmb_filtroBusqueda;
    private javax.swing.JComboBox<String> cmb_mes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_filtroDeBusqueda;
    private javax.swing.JLabel jLabel_sinRegistros;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_movimientos;
    // End of variables declaration//GEN-END:variables

}
