package ventanas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import clases.Usuarios;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Login extends javax.swing.JFrame {

    private String user, pass;
    int validacion = 0, idUsuario;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Iniciar sesión");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //setSize(300,350)
        pack();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                new Inicio().setVisible(true);
                dispose();
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_iniciarSesion = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Iniciar sesión");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txt_user.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        txt_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, -1));

        btn_iniciarSesion.setBackground(new java.awt.Color(52, 152, 219));
        btn_iniciarSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_iniciarSesion.setForeground(new java.awt.Color(242, 242, 242));
        btn_iniciarSesion.setText("Iniciar sesión");
        btn_iniciarSesion.setBorder(null);
        btn_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 175, 130, 35));

        btn_cancelar.setBackground(new java.awt.Color(108, 117, 125));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(242, 242, 242));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(null);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 220, 130, 30));

        jLabel_wallpaper.setBackground(new java.awt.Color(245, 247, 250));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarSesionActionPerformed
        // TODO add your handling code here:

        validacion = 0;

        //validar campos vacios
        user = txt_user.getText().trim();
        if (user.equals("")) {
            txt_user.setBackground(Color.red);
            validacion++;
        }
        pass = new String(txt_password.getPassword());
        if (pass.equals("")) {
            txt_password.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {

            try {
                Usuarios u = new Usuarios(user, pass);
                pass = null;
                idUsuario = u.login();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this,
                        "No se pudo acceder a la base de datos SQLite.\n\n"
                        + "Verifique que el archivo 'bd_fm.db' exista y no esté en uso.",
                        "Error de conexión",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            //Login
            if (idUsuario > 0) {
                Principal p = new Principal(user, idUsuario);
                p.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Usuario o contraseña incorrectos.\nVerifique sus datos e intente nuevamente.",
                        "Error de autenticación",
                        JOptionPane.ERROR_MESSAGE);
                Limpiar();
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Faltan campos por completar.\nPor favor llene todos los datos antes de continuar.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);

            txt_user.setBackground(Color.white);
            txt_password.setBackground(Color.white);
        }
    }//GEN-LAST:event_btn_iniciarSesionActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        volverAInicio();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void volverAInicio() {
        this.dispose();
        new Inicio().setVisible(true);
    }

    private void Limpiar() {
        txt_password.setText("");
        txt_user.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
