package ventanas;

import clases.Movimientos;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    String user;
    int idUsuario;
    double saldo, totalIngresos, totalEgresos;
    private Movimientos m;
    NumberFormat formato = NumberFormat.getCurrencyInstance();

    public Principal(String user, int idUsuario) {
        this.idUsuario = idUsuario;
        this.user = user;
        
        initComponents();
        
        m = new Movimientos();

        mostrarUsuario();
        mostrarSaldo();
        totalIngresos();
        totalEgresos();

        setTitle("Bienvenido, " + user);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //setSize(400,300)
        pack();

        ImageIcon icono = new ImageIcon(getClass().getResource("/images/AgregarMovimiento.png"));
        Image img = icono.getImage().getScaledInstance(170, 50, Image.SCALE_SMOOTH);
        btn_agregarMovimiento.setIcon(new ImageIcon(img));

        ImageIcon icono2 = new ImageIcon(getClass().getResource("/images/HistorialDeMovimientos.png"));
        Image img2 = icono2.getImage().getScaledInstance(170, 50, Image.SCALE_SMOOTH);
        btn_historial.setIcon(new ImageIcon(img2));

    }

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    private void mostrarUsuario() {
        jLabel_titulo.setText("Bienvenido, " + user);
    }

    public void mostrarSaldo() {
        saldo = m.calcularSaldo(idUsuario);

        jLabel_saldoActual.setText("Saldo actual: " + formato.format(saldo));
    }

    public void totalIngresos() {
        totalIngresos = m.calcularTotalIngresos(idUsuario);

        jLabel_totalIngresos.setText("Total Ingresos: " + formato.format(totalIngresos));
    }

    public void totalEgresos() {
        totalEgresos = m.calcularTotalEgresos(idUsuario);

        jLabel_totalEgresos.setText("Total Egresos: " + formato.format(totalEgresos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_saldoActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_agregarMovimiento = new javax.swing.JButton();
        btn_historial = new javax.swing.JButton();
        jLabel_totalIngresos = new javax.swing.JLabel();
        jLabel_totalEgresos = new javax.swing.JLabel();
        btn_cerrarSesion = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_ayuda = new javax.swing.JMenu();
        jMenuItem_acerdade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_titulo.setText("Bienvenido, ");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel_saldoActual.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_saldoActual.setText("Saldo actual: $");
        getContentPane().add(jLabel_saldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona una opción ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        btn_agregarMovimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_agregarMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_agregarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 50));

        btn_historial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historialActionPerformed(evt);
            }
        });
        getContentPane().add(btn_historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 50));

        jLabel_totalIngresos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_totalIngresos.setText("Total Ingresos: $");
        getContentPane().add(jLabel_totalIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel_totalEgresos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_totalEgresos.setText("Total Egresos: $");
        getContentPane().add(jLabel_totalEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        btn_cerrarSesion.setBackground(new java.awt.Color(220, 53, 69));
        btn_cerrarSesion.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_cerrarSesion.setForeground(new java.awt.Color(242, 242, 242));
        btn_cerrarSesion.setText("Cerrar sesión");
        btn_cerrarSesion.setBorder(null);
        btn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, 30));

        jLabel_wallpaper.setBackground(new java.awt.Color(245, 247, 250));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        jMenu_ayuda.setText("Ayuda");

        jMenuItem_acerdade.setText("Acerca de");
        jMenuItem_acerdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_acerdadeActionPerformed(evt);
            }
        });
        jMenu_ayuda.add(jMenuItem_acerdade);

        jMenuBar1.add(jMenu_ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historialActionPerformed
        // TODO add your handling code here:
        HistorialMovimientos hm = new HistorialMovimientos(this, true, idUsuario, user);
        hm.setVisible(true);
    }//GEN-LAST:event_btn_historialActionPerformed

    private void btn_agregarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarMovimientoActionPerformed
        // TODO add your handling code here:
        AgregarMovimiento am = new AgregarMovimiento(this, true, idUsuario);
        am.setVisible(true);
    }//GEN-LAST:event_btn_agregarMovimientoActionPerformed

    private void btn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSesionActionPerformed
        // TODO add your handling code here:
        int eleccion = JOptionPane.showConfirmDialog(this, "¿Deseas cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);

        if (eleccion == JOptionPane.YES_OPTION) {
            volverAInicio();
        }
    }//GEN-LAST:event_btn_cerrarSesionActionPerformed

    private void jMenuItem_acerdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_acerdadeActionPerformed
        // TODO add your handling code here:
        AcercaDe ad = new AcercaDe(this, true);
        ad.setVisible(true);
    }//GEN-LAST:event_jMenuItem_acerdadeActionPerformed

    private void volverAInicio(){
        this.dispose();
        new Inicio().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarMovimiento;
    private javax.swing.JButton btn_cerrarSesion;
    private javax.swing.JButton btn_historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_saldoActual;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_totalEgresos;
    private javax.swing.JLabel jLabel_totalIngresos;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_acerdade;
    private javax.swing.JMenu jMenu_ayuda;
    // End of variables declaration//GEN-END:variables
}
