package ventanas;

import clases.Usuarios;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

public class Registrarse extends javax.swing.JFrame {

    String user = "", pass = "", confirmarPass = "", saldoInicial = "";
    double saldoI;
    int validacion = 0;

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrarse");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //setSize(300,450);
        pack();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                new Inicio().setVisible(true);
                dispose();
            }
        });

    }

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icono.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_saldoInicial = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmarPassword = new javax.swing.JPasswordField();
        btn_registrarse = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_titulo.setText("Registrarse");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Saldo inicial:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, -1, -1));

        txt_user.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));

        txt_saldoInicial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_saldoInicial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_saldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 205, 130, -1));

        txt_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, -1));

        txt_confirmarPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_confirmarPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_confirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 130, -1));

        btn_registrarse.setBackground(new java.awt.Color(39, 174, 96));
        btn_registrarse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_registrarse.setForeground(new java.awt.Color(242, 242, 242));
        btn_registrarse.setText("Registrarse");
        btn_registrarse.setBorder(null);
        btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 270, 130, 35));

        btn_cancelar.setBackground(new java.awt.Color(108, 117, 125));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(242, 242, 242));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(null);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 315, 130, 30));

        jLabel_wallpaper.setBackground(new java.awt.Color(245, 247, 250));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarseActionPerformed
        // TODO add your handling code here:

        validacion = 0;

        //Recuperar datos
        user = txt_user.getText().trim();
        pass = txt_password.getText().trim();
        confirmarPass = txt_confirmarPassword.getText();
        saldoInicial = txt_saldoInicial.getText().trim();

        if (user.equals("")) {
            txt_user.setBackground(Color.red);
            validacion++;
        }
        if (pass.equals("")) {
            txt_password.setBackground(Color.red);
            validacion++;
        }
        if (confirmarPass.equals("")) {
            txt_confirmarPassword.setBackground(Color.red);
            validacion++;
        }
        if (saldoInicial.equals("")) {
            txt_saldoInicial.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {
            //Comparar contraseñas
            if (!pass.equals(confirmarPass)) {
                JOptionPane.showMessageDialog(this,
                        "Las contraseñas no coinciden.\nPor favor, verifique e intente nuevamente.",
                        "Error de validación",
                        JOptionPane.WARNING_MESSAGE);
                txt_password.setText("");
                txt_confirmarPassword.setText("");
                return;
            }

            //validar saldo inicial
            try {
                saldoI = Double.parseDouble(saldoInicial);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El saldo inicial debe contener solo números.\nPor favor ingrese un valor válido.",
                        "Formato incorrecto",
                        JOptionPane.WARNING_MESSAGE);
                txt_saldoInicial.setText("");
                return;
            }

            //validar saldo positivo
            if (saldoI <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El saldo inicial debe ser mayor que cero.\nIngrese un valor positivo para continuar.",
                        "Valor inválido",
                        JOptionPane.WARNING_MESSAGE);

                txt_saldoInicial.setText("");
                return;
            }

            //Mandar los datos al constructor
            pass = txt_password.getText();
            Usuarios usuario = new Usuarios(user, pass, saldoI);
            pass = null;

            //validar user existente
            try {

                if (usuario.registrar()) {
                    JOptionPane.showMessageDialog(this,
                            "Registro exitoso.\nAhora puede iniciar sesión.",
                            "Registro completado",
                            JOptionPane.INFORMATION_MESSAGE);
                    volverAInicio();
                }

            } catch (IllegalStateException e) {

                JOptionPane.showMessageDialog(this,
                        "El nombre de usuario ya está registrado.\nPor favor elige otro diferente.",
                        "Usuario no disponible",
                        JOptionPane.WARNING_MESSAGE);

                txt_user.setText("");

            } catch (RuntimeException e) {

                JOptionPane.showMessageDialog(this,
                        "No se pudo conectar con la base de datos.\n\n"
                        + "No se pudo conectar con la base de datos local.\nVerifique que el servicio MySQL esté activo y vuelva a intentarlo.",
                        "Error de conexión",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Faltan campos por completar.\nPor favor llene todos los datos antes de continuar.",
                    "Campos incompletos",
                    JOptionPane.WARNING_MESSAGE);

            txt_user.setBackground(Color.white);
            txt_password.setBackground(Color.white);
            txt_confirmarPassword.setBackground(Color.white);
            txt_saldoInicial.setBackground(Color.white);

        }


    }//GEN-LAST:event_btn_registrarseActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicio in = new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void volverAInicio() {
        this.dispose();
        new Inicio().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_registrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPasswordField txt_confirmarPassword;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_saldoInicial;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

}
